CREATE TABLE `appointments` (
  `SN` int NOT NULL AUTO_INCREMENT,
  `APPOINTMENT_DATE` date NOT NULL,
  `APPOINTMENT_TIME` time NOT NULL,
  `APPOINTMENT_STATUS` char(1) NOT NULL,
  `DOCTOR_ID` int DEFAULT NULL,
  `PATIENT_ID` int DEFAULT NULL,
  PRIMARY KEY (`SN`),
  KEY `Doctor_FK_idx` (`DOCTOR_ID`),
  KEY `Patients_FK_idx` (`PATIENT_ID`),
  CONSTRAINT `Doctor_FK` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `doctors` (`SN`),
  CONSTRAINT `Patients_FK` FOREIGN KEY (`PATIENT_ID`) REFERENCES `users_db`.`patients` (`SN`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
