CREATE TABLE `doctors` (
  `SN` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `PHONE` char(11) NOT NULL,
  `SPECIALIZATION` int NOT NULL,
  PRIMARY KEY (`SN`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  KEY `SN_idx` (`SPECIALIZATION`),
  CONSTRAINT `Specialization_FK` FOREIGN KEY (`SPECIALIZATION`) REFERENCES `specializations` (`SN`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
